version: '2'
networks:
  dpm_network:
    name: "${DPM_NETWORK:-sca_fose_network}"

services:
  zookeeper:
    container_name: zookeeper
    image: path-to-image/zookeeper/zookeeper:7.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - "${SCA_FOSE_NETWORK:-sca_fose_network}"
  kafka:
    container_name: kafka
    image: path-to-image/kafka/kafka:7.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - "${SCA_FOSE_NETWORK:-sca_fose_network}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
